### PR TITLE
fix: adding custom release note to goreleaser

### LINKED ISSUE #257: Releases don't show complete changelog
**Describe the bug**
In Releases page: https://github.com/datreeio/datree/releases you don't see the full changelog between the current and previous release

**To Reproduce**
Go to releases page: https://github.com/datreeio/datree/releases

**Expected behavior**
in a release, see the full changelog

**Screenshots**
Screen Shot 2021-10-31 at 13 38 19

**Desktop (please complete the following information):**
 - OS: not relevant

**Datree version (run `datree version`):**
 - Version: not relevant

### PR DESCRIPTION
**Pull request by shmuelsa**

### CODE REVIEW

File: scripts/custom_changelog.sh [hunk 1]
```diff
@@ -0,0 +1,7 @@
+#!/bin/bash
+set -ex
+
+latestRelease=$(git tag --sort=-version:refname | grep "\-rc$" | head -n 1)
+customChangeLog=$(git log --pretty="%h %N %s%n" --decorate=full ${latestRelease//-rc}..HEAD)
+
+echo $customChangeLog
```
Comment (royhadad) [inline scripts/custom_changelog.sh]: maybe add new line at end of file

File: scripts/release.sh [hunk 2]
```diff
@@ -13,7 +13,8 @@ bash ./scripts/sign_application.sh
 export DATREE_BUILD_VERSION=$release_tag
 echo $DATREE_BUILD_VERSION
 
-curl -sL https://git.io/goreleaser | GORELEASER_CURRENT_TAG=$DATREE_BUILD_VERSION GO_BUILD_TAG=main VERSION=v$GORELEASER_VERSION bash
+custom_changelog_output=$(./scripts/custom_changelog.sh)
+curl -sL https://git.io/goreleaser | GORELEASER_CURRENT_TAG=$DATREE_BUILD_VERSION GO_BUILD_TAG=main VERSION=v$GORELEASER_VERSION bash -s -- --rm-dist --release-notes <($custom_changelog_output)
```
Comment (royhadad) [inline scripts/release.sh:17]: check if --rm-dist is required

File: scripts/custom_changelog.sh [hunk 3]
```diff
@@ -0,0 +1,7 @@
+#!/bin/bash
```
Comment (royhadad) [inline scripts/custom_changelog.sh:1]: delete the uneeded code from ".goreleaser.yml"

**Review by dimabru — APPROVED** [review]
