### PR TITLE
fix: add check in wereViolationsFound to fix error with --only-k8s-fi…

### LINKED ISSUE #430: Running test on non k8s yaml files with `--only-k8s-files` flag raises an error
**Describe the bug**
Running `datree test` on non k8s files with `--only-k8s-files` flag raises invalid memory address or nil pointer dereference error on runtime

**To Reproduce**
1. Run command 'datree test internal/fixtures/kube/Chart.yaml --only-k8s-files'
2. See error

**Expected behavior**
Suppose to show test results - this file/these files should be presented with their invalidation error

**Screenshots**
Screen Shot 2022-02-23 at 12 29 38

**Desktop (please complete the following information):**
 - OS: macOs Monterey
 
**Datree version:**
 - Version: 0.15.22

### PR DESCRIPTION
**Pull request by royhadad**
…les bug

### CODE REVIEW

**Review by dimabru — DISMISSED** [review]

File: cmd/test/main.go [hunk 1]
```diff
@@ -473,5 +473,13 @@ func evaluate(ctx *TestCommandContext, filesPaths []string, prerunData *TestComm
...
-	return (validationManager.InvalidYamlFilesCount() > 0 || validationManager.InvalidK8sFilesCount() > 0 || results.EvaluationResults.Summary.TotalFailedRules > 0)
+	if validationManager.InvalidYamlFilesCount() > 0 {
+		return true
+	} else if validationManager.InvalidK8sFilesCount() > 0 {
+		return true
+	} else if results.EvaluationResults != nil && results.EvaluationResults.Summary.TotalFailedRules > 0 {
+		return true
+	} else {
+		return false
+	}
```
Comment (TzlilSwimmer123) [inline cmd/test/main.go:484]: You can remove the last else and just return false in the end - maybe it's prettier

**Review by TzlilSwimmer123 — APPROVED** [review]
