### PR TITLE
fix: add darwin case with os architecture point to x86_64

### LINKED ISSUE #304: installation with "curl" doesn't work with mac m1 chip
**description**
installation with "curl" doesn't work with mac m1 chip

**Steps to reproduce the behavior:**
1. open a mac machine with an m1 chip
2. run the datree installation command: "curl https://get.datree.io | /bin/bash"
3. run "datree --help"
4. you will get an error: "datree: command not found"

**Expected behavior**
Expecting the datree cli to be installed

 - OS: MacOS, m1 chip
 - Version: 0.14.62

### PR DESCRIPTION
**Pull request by shmuelsa**

### CODE REVIEW

**Review by royhadad — DISMISSED** [review]

File: install.sh [hunk 1]
```diff
@@ -5,13 +5,17 @@ set -e
...
+if [ $osName == "Darwin" ]; then
+    osArchitecture='x86_64'
+elif [[ $osArchitecture == *'aarch'* || $osArchitecture == *'arm'* ]]; then
 	osArchitecture='arm64'
 fi
 
 DOWNLOAD_URL=$(curl --silent "https://api.github.com/repos/datreeio/datree/releases/latest" | grep -o "browser_download_url.*\_${osName}_${osArchitecture}.zip")
 DOWNLOAD_URL=${DOWNLOAD_URL//\"}
 DOWNLOAD_URL=${DOWNLOAD_URL/browser_download_url: /}
+echo $DOWNLOAD_URL
```
Comment (myishay) [inline install.sh]: remove this line

**Review by myishay — DISMISSED** [review]

File: install.sh [hunk 2]
```diff
@@ -5,14 +5,18 @@ set -e
 osName=$(uname -s)
 
 osArchitecture=$(uname -m)
-if [[ $osArchitecture == *'aarch'* || $osArchitecture == *'arm'* ]]; then
+
+if [ $osName == "Darwin" ]; then
```
Comment (dimabru) [inline install.sh]: We need to make this release to only work for `M1` arch and `x86_64` to avoid installing this executable for any other architectures

**Review by royhadad — APPROVED** [review]
