### PR TITLE
fix: use k8s sigs yaml for marshaling while extracting k8s objects

### LINKED ISSUE #762: Unexpected yaml validation error: did not find expected '-' indicator
**Describe the bug**

This is a valid YAML file, but datree displays the error `yaml validation error: yaml: line 15: did not find expected '-' indicator`

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-name
  annotations:
    datree.skip/CONTAINERS_MISSING_LIVENESSPROBE_KEY: skipping for Job
    datree.skip/CONTAINERS_MISSING_READINESSPROBE_KEY: skipping for Job
spec:
  activeDeadlineSeconds: 300 # give up after N seconds
  template:
    spec:
      restartPolicy: OnFailure # restart the pod on failure instead of re-creating a pod each time
      containers:
        - name: app
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - bash
          args:
            - "-c"
            - |
              
              echo "hello world"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

```

**To Reproduce**
1. Run command `datree test this_is_valid.yaml`
2. See error `yaml validation error: yaml: line 15: did not find expected '-' indicator`

**Expected behavior**
No error

But if I modify as below, it can be validated by datree
```diff
apiVersion: batch/v1
kind: Job
metadata:
  name: job-name
  annotations:
    datree.skip/CONTAINERS_MISSING_LIVENESSPROBE_KEY: skipping for Job
    datree.skip/CONTAINERS_MISSING_READINESSPROBE_KEY: skipping for Job
spec:
  activeDeadlineSeconds: 300 # give up after N seconds
  template:
    spec:
      restartPolicy: OnFailure # restart the pod on failure instead of re-creating a pod each time
      containers:
        - name: app
          image: "artifactory-prod.netskope.io/stork-production/epdlp-utils-image:0.0.0"
          imagePullPolicy: IfNotPresent
          command:
            - bash
          args:
            - "-c"
            - |
-              
              echo "hello world"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

```

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: MAcOS
**Datree version (run `datree version`):**
 - Version: 1.6.6
**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: https://app.datree.io/login?t=53x2ZDovu28inkAAMgQzzo

### PR DESCRIPTION
**Pull request by myishay**

### CODE REVIEW

File: pkg/extractor/extractor.go [hunk 1]
```diff
@@ -101,7 +101,7 @@ func extractYamlConfigurations(content string) (*[]Configuration, error) {
 			}
 		}
 
-		yamlByteArray, err := yaml.Marshal(anyTypeStore)
```
Comment (TzlilSwimmer123) [inline pkg/extractor/extractor.go:104]: where is the import?

Comment (myishay) [reply pkg/extractor/extractor.go:104]: `yamlConvertor` is already imported previously

**Review by TzlilSwimmer123 — APPROVED** [review]
I assume we need to do some tests to check it works properly, maybe you already did it so I am ok with it!
