### PR TITLE
fix: error messages logged to stderr instead of stdout

### LINKED ISSUE #900: Error messages logged to stdout instead of stderr break Json and Yaml output formats
**Describe the bug**
When an either 
a) an error is thrown 
b) running in offline mode
with `--output json` or `--output yaml` flag set, the resulting error messages are logged to stdout. This results in non conforment json or yaml output.  

**To Reproduce**
1. Run command 'datree test ./ --output json` in a directory containing no yaml files
2. See `no files detected` logged in non-json to stdout

1. Run command `datree config set offline local`
2. Run command `datree test ./ --no-record`

```
...
"evaluationSummary":{"configsCount":11,"filesCount":10,"passedYamlValidationCount":10,"k8sValidation":"10/10","passedPolicyValidationCount":7},"yamlValidationResults":null,"k8sValidationResults":null,"loginUrl":""}
[INFO] You're running Datree in offline mode

```

**Expected behavior**
Errors and warnings are logged to stderr so stdout so output can be compliant with the configured output format (eg. json or yaml). 

**Screenshots**
Screenshot 2023-03-13 at 8 06 37 am

**Desktop (please complete the following information):**
 - OS: MacOS

**Datree version (run `datree version`):**
 - Version: 1.8.39

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: ktqUgZurDdKM56Fe8kDJi7

**Additional context**  
Note that the latest version v1.8.39 introduced additional logging in offline mode which will result in output being no longer json or yaml compliant. Pre-existing issues with errors such as `no files detected` were already logged to stdout opposed to stderr so this is still a bug in addition to the regression.

### PR DESCRIPTION
**Pull request by shmu3l**
**test case:** 
`./datree test ~/.datree/k8s-demo.yam -o json 1>stdout.log 2> error.log`

image

**info new line**

image

**format output:** 

`./datree test ~/.datree/k8s-demo.yaml -o json | jq`

image

### CODE REVIEW

**Review by royhadad — DISMISSED** [review]

File: cmd/test/main.go [hunk 1]
```diff
@@ -467,8 +468,8 @@ func test(ctx *TestCommandContext, paths []string, testCommandData *TestCommandD
 		}
 	}
 
-	if testCommandData.IsOffline {
-		ctx.Printer.PrintMessage("[INFO] You're running Datree in offline mode", "cyan")
+	if testCommandData.IsOffline && testCommandData.Output == "" {
```
Comment (royhadad) [inline cmd/test/main.go]: use `&& !IsFormattedOutputOption(testCommandData.Output)` instead

**Review by royhadad — CHANGES_REQUESTED** [review]

**Review by royhadad — DISMISSED** [review]

**Review by royhadad — APPROVED** [review]
